services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: mecanicosya_admin
      POSTGRES_PASSWORD: mecanicosya_admin_pass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - mecanicosya-postgres-data:/var/lib/postgresql/data
      - ./infra/postgres/init-databases.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mecanicosya_admin -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mecanicosya-postgres-data:
